In [198]:
import pandas as pd

In [199]:
test_data  = pd.read_csv('../data/customer_churn_dataset-testing-master.csv')
train_data = pd.read_csv('../data/customer_churn_dataset-training-master.csv')

In [200]:
print(train_data.shape)
print(test_data.shape)
train_data.head()
train_data.info()
train_data['Churn'].value_counts()

(440833, 12)
(64374, 12)
<class 'pandas.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  str
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  str
 8   Contract Length    440832 non-null  str
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), str(3)
memory usage: 40.4 MB

Churn
1.0    249999
0.0    190833
Name: count, dtype: int64

In [201]:
print(train_data['Gender'].unique())
print(train_data['Subscription Type'].unique())
print(train_data['Contract Length'].unique())

<StringArray>
['Female', 'Male', nan]
Length: 3, dtype: str
<StringArray>
['Standard', 'Basic', 'Premium', nan]
Length: 4, dtype: str
<StringArray>
['Annual', 'Monthly', 'Quarterly', nan]
Length: 4, dtype: str

In [202]:
train_data.describe()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000
mean,225398.667955,39.373153,31.256336,15.807494,3.604437,12.965722,631.616223,14.480868,0.567107
std,129531.918550,12.442369,17.255727,8.586242,3.070218,8.258063,240.803001,8.596208,0.495477
min,2.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,113621.750000,29.000000,16.000000,9.000000,1.000000,6.000000,480.000000,7.000000,0.000000
50%,226125.500000,39.000000,32.000000,16.000000,3.000000,12.000000,661.000000,14.000000,1.000000
75%,337739.250000,48.000000,46.000000,23.000000,6.000000,19.000000,830.000000,22.000000,1.000000
max,449999.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [203]:
train_data = train_data.dropna(axis = 0)
train_data = train_data.drop(columns=['CustomerID'])
train_data.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [204]:
train_data['Gender'] = train_data['Gender'].map({'Male':1,'Female':0})
train_data = pd.get_dummies(train_data, columns=['Subscription Type','Contract Length'],drop_first= True) 
train_X = train_data.drop(columns=['Churn'])
train_y = train_data['Churn']

In [205]:
train_data.head()
#train_data.columns.to_list()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,30.0,0,39.0,14.0,5.0,18.0,932.0,17.0,1.0,False,True,False,False
1,65.0,0,49.0,1.0,10.0,8.0,557.0,6.0,1.0,False,False,True,False
2,55.0,0,14.0,4.0,6.0,18.0,185.0,3.0,1.0,False,False,False,True
3,58.0,1,38.0,21.0,7.0,7.0,396.0,29.0,1.0,False,True,True,False
4,23.0,1,32.0,20.0,5.0,8.0,617.0,20.0,1.0,False,False,True,False

In [175]:
test_data.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,22,0,25,14,4,27,598,9,1,False,False,True,False
1,41,0,28,28,7,13,584,20,0,False,True,True,False
2,47,1,27,10,2,29,757,21,0,True,False,False,False
3,35,1,9,12,5,17,232,18,0,True,False,False,True
4,53,0,58,24,9,2,533,18,0,False,True,False,False

In [206]:
test_data = test_data.dropna(axis=0)
test_data = test_data.drop(columns= ['CustomerID'])
test_data['Gender'] = test_data['Gender'].map({'Male':1, 'Female':0})
test_data = pd.get_dummies(test_data, columns=['Subscription Type', 'Contract Length'], drop_first= True)

In [155]:
test_X = test_data.drop(columns=['Churn'])
test_y = test_data['Churn']

In [208]:
print(train_X.columns.to_list())
print(test_X.columns.to_list())

['Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Total Spend', 'Last Interaction', 'Subscription Type_Premium', 'Subscription Type_Standard', 'Contract Length_Monthly', 'Contract Length_Quarterly']
['Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Total Spend', 'Last Interaction', 'Subscription Type_Premium', 'Subscription Type_Standard', 'Contract Length_Monthly', 'Contract Length_Quarterly']

In [222]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_X_scaled = scaler.fit_transform(train_X)
test_X_scaled  = scaler.transform(test_X)

In [223]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=100)
log_model.fit(train_X_scaled,train_y)
log_preds = log_model.predict(test_X_scaled)

In [224]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy Test: {}\n".format(accuracy_score(log_preds, test_y)))
print("Classification Report: \n{}\n".format(classification_report(test_y, log_preds)))
print("Confusion matrix: \n {}\n".format(confusion_matrix(test_y,log_preds)))

Accuracy Test: 0.8480928722709369

Classification Report:
              precision    recall  f1-score   support

         0.0       0.82      0.85      0.83     44943
         1.0       0.88      0.85      0.86     56099

    accuracy                           0.85    101042
   macro avg       0.85      0.85      0.85    101042
weighted avg       0.85      0.85      0.85    101042


Confusion matrix:
 [[38164  6779]
 [ 8570 47529]]

In [225]:
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier(random_state= 1, max_depth= 5, min_samples_leaf=50)
tree_model.fit(train_X,train_y)
tree_preds = tree_model.predict(test_X)

In [226]:
print("Accuracy Score: {}".format(accuracy_score(test_y,tree_preds)))
print("Classification Report: \n {}".format(classification_report(test_y,tree_preds)))
print("Confusion Matrix: \n{}".format(confusion_matrix(test_y,tree_preds)))

Accuracy Score: 0.9187862473031017
Classification Report:
               precision    recall  f1-score   support

         0.0       0.95      0.86      0.90     44943
         1.0       0.90      0.97      0.93     56099

    accuracy                           0.92    101042
   macro avg       0.92      0.91      0.92    101042
weighted avg       0.92      0.92      0.92    101042

Confusion Matrix:
[[38667  6276]
 [ 1930 54169]]

In [229]:
train_pred = tree_model.predict(train_X)
print("Training accuracy: ", accuracy_score(train_y, train_pred))

Training accuracy:  0.9181520372917924

In [186]:
print("Correlation with Churn (train):")
print(train_data.corr(numeric_only=True)['Churn'].sort_values(ascending=False))

print("\nCorrelation with Churn (test):")
print(test_data.corr(numeric_only=True)['Churn'].sort_values(ascending=False))

Correlation with Churn (train):
Churn               1.000000
Support Calls       0.574267
Payment Delay       0.312129
Age                 0.218394
Last Interaction    0.149616
Usage Frequency    -0.046101
Tenure             -0.051919
Total Spend        -0.429355
CustomerID         -0.839365
Name: Churn, dtype: float64

Correlation with Churn (test):
Churn               1.000000
Payment Delay       0.557386
CustomerID          0.529832
Support Calls       0.304631
Tenure              0.195327
Age                 0.063457
Last Interaction   -0.002818
Total Spend        -0.078867
Usage Frequency    -0.115098
Name: Churn, dtype: float64

In [221]:
combined_df = pd.concat([train_data, test_data], ignore_index=True)

from sklearn.model_selection import train_test_split
X = combined_df.drop(columns=['Churn'])
y = combined_df['Churn']

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)

In [227]:
from sklearn.ensemble import RandomForestClassifier

forest_model = RandomForestClassifier(n_estimators=100, random_state=1)
forest_model.fit(train_X,train_y)
forest_predict = forest_model.predict(test_X)

In [228]:
print("Accuracy: ", accuracy_score(test_y, forest_predict))
print("Classification Report: \n",classification_report(test_y,forest_predict))
print("Confusion Matrix: \n", confusion_matrix(test_y,forest_predict))

Accuracy:  0.9364818590289187
Classification Report:
               precision    recall  f1-score   support

         0.0       1.00      0.86      0.92     44943
         1.0       0.90      1.00      0.95     56099

    accuracy                           0.94    101042
   macro avg       0.95      0.93      0.93    101042
weighted avg       0.94      0.94      0.94    101042

Confusion Matrix:
 [[38658  6285]
 [  133 55966]]

In [231]:
importances = pd.Series(forest_model.feature_importances_, index=train_X.columns)
importances = importances.sort_values(ascending=False)
print(importances)

Support Calls                 0.266530
Total Spend                   0.193355
Age                           0.135419
Payment Delay                 0.133630
Contract Length_Monthly       0.092599
Last Interaction              0.058820
Tenure                        0.040785
Usage Frequency               0.031717
Gender                        0.030057
Contract Length_Quarterly     0.007021
Subscription Type_Standard    0.005059
Subscription Type_Premium     0.005009
dtype: float64